services:
  postgres:
    image: postgres:17
    container_name: postgres17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: Pass
      POSTGRES_DB: credit-passport
    restart: unless-stopped