server:
  port: 8080

spring:
  application:
    name: credit-passport

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/credit-passport
    username: finance
    password: Pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ianmwirigi638@gmail.com
    password: cxgtocarqafxjfjv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    jwt:
      secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      access-token-expiry-ms: 900000
      refresh-token-expiry-days: 2